info:
  title: Product API
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Get all products
      description: Retrieve a list of all products.
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      description: Create a new product.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: The newly created product
  /api/products/{id}:
    get:
      summary: Get a product by ID
      description: Retrieve a specific product by its ID.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        '200':
          description: The requested product
        '404':
          description: Product not found
    put:
      summary: Update a product
      description: Update an existing product.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the product
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: The updated product
        '404':
          description: Product not found
    delete:
      summary: Delete a product
      description: Delete an existing product.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the product.
        name:
          type: string
          description: The name of the product.
        description:
          type: string
          description: A brief description of the product.
